### ISSUE TITLE
"Failed to execute script Sounder"

### ISSUE THREAD

**Issue by kbjay01** [losek1/Py_MusicPlayer#2]
If you are starting sounder app you have to select a directory that will show where are music files located. The problem is, that if you will start app and you won't select any directory, the program will say **_Failed to execute script Sounder_** and exit, that's fine but, if you're trying to start app again **you can't choose new directory**, so app keeps on saying **_Failed to execute script Sounder_**, and I can't do anything because it's closing and I can't choose a new directory. Please fix

**Comment by losek1** [comment]
Try deleting sounder install dir.
Then reinstall sounder 2.6.7

**Comment by losek1** [comment]
The issue has been fixed!

**Comment by losek1** [comment]
I hope it worked <3
